from dataclasses import dataclass
import typing
import typing_extensions
from dataclasses import dataclass
from enum import Enum

from flytekit.core.annotation import (
    FlyteAnnotation,
)

from latch.types.metadata import (
    NextflowParameter,
)
from latch.types.file import LatchFile
from latch.types.directory import (
    LatchDir,
    LatchOutputDir,
)


class annotation_database(Enum):
    bakta = "bakta"
    prodigal = "prodigal"
    pyrodigal = "pyrodigal"
    prokka = "prokka"


class ampir_model(Enum):
    precursor = "precursor"
    mature = "mature"


@dataclass
class Samplesheet:
    sample: str
    fasta: LatchFile
    protein: typing.Optional[LatchFile]
    gbk: typing.Optional[LatchFile]


# Import these into your `__init__.py` file:
#
# from .parameters import generated_parameters

generated_parameters = {
    "input": NextflowParameter(
        type=typing.List[Samplesheet],
        display_name="Input",
        description="Information about the samples in the experiment",
        section_title=None,
        samplesheet_type="csv",
        samplesheet=True,
        default=None,
    ),
    "outdir": NextflowParameter(
        type=typing_extensions.Annotated[
            LatchDir,
            FlyteAnnotation(
                {"output": True}
            ),
        ],
        default=None,
        section_title=None,
        description="The output directory where the results will be saved. You have to use absolute paths to storage on Cloud infrastructure.",
        display_name="Outdir",
    ),
    "email": NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description="Email address for completion summary.",
        display_name="Email",
    ),
    "multiqc_title": NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description="MultiQC report title. Printed as page header, used for filename if not otherwise specified.",
        display_name="MultiQC Title",
    ),
    "run_amp_screening": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate antimicrobial peptide genes screening tools.",
        display_name="Run AMP Screening",
    ),
    "run_arg_screening": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate antimicrobial resistance gene screening tools.",
        display_name="Run ARG Screening",
    ),
    "run_bgc_screening": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate biosynthetic gene cluster screening tools.",
        display_name="Run BGC Screening",
    ),
    "run_taxa_classification": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activates the taxonomic classification of input nucleotide sequences.",
        display_name="Run Taxa Classification",
    ),
    "taxa_classification_tool": NextflowParameter(
        type=typing.Optional[str],
        default="mmseqs2",
        section_title=None,
        description="Specifies the tool used for taxonomic classification.",
        display_name="Taxa Classification Tool",
    ),
    "taxa_classification_mmseqs_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Specify a path to MMseqs2-formatted database.",
        display_name="Taxa Classification MMseqs DB",
    ),
    "taxa_classification_mmseqs_db_id": NextflowParameter(
        type=typing.Optional[str],
        default="Kalamari",
        section_title=None,
        description="Specify the label of the database to be used.",
        display_name="Taxa Classification MMseqs DB ID",
    ),
    "taxa_classification_mmseqs_db_savetmp": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether the temporary files should be saved.",
        display_name="Taxa Classification MMseqs DB Save Tmp",
    ),
    "taxa_classification_mmseqs_taxonomy_savetmp": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether to save the temporary files.",
        display_name="Taxa Classification MMseqs Taxonomy Save Tmp",
    ),
    "taxa_classification_mmseqs_taxonomy_searchtype": NextflowParameter(
        type=typing.Optional[int],
        default=2,
        section_title=None,
        description="Specify the alignment type between database and query.",
        display_name="Taxa Classification MMseqs Taxonomy Search Type",
    ),
    "taxa_classification_mmseqs_taxonomy_lcaranks": NextflowParameter(
        type=typing.Optional[str],
        default="kingdom,phylum,class,order,family,genus,species",
        section_title=None,
        description="Specify the taxonomic levels to display in the result table.",
        display_name="Taxa Classification MMseqs Taxonomy LCA Ranks",
    ),
    "taxa_classification_mmseqs_taxonomy_taxlineage": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Specify whether to include or remove the taxonomic lineage.",
        display_name="Taxa Classification MMseqs Taxonomy Tax Lineage",
    ),
    "taxa_classification_mmseqs_taxonomy_sensitivity": NextflowParameter(
        type=typing.Optional[str],
        default="5.0",
        section_title=None,
        description="Specify the speed and sensitivity for taxonomy assignment.",
        display_name="Taxa Classification MMseqs Taxonomy Sensitivity",
    ),
    "taxa_classification_mmseqs_taxonomy_orffilters": NextflowParameter(
        type=typing.Optional[str],
        default="2.0",
        section_title=None,
        description="Specify the ORF search sensitivity in the prefilter step.",
        display_name="Taxa Classification MMseqs Taxonomy ORF Filters",
    ),
    "taxa_classification_mmseqs_taxonomy_lcamode": NextflowParameter(
        type=typing.Optional[int],
        default=3,
        section_title=None,
        description="Specify the mode to assign the taxonomy.",
        display_name="Taxa Classification MMseqs Taxonomy LCA Mode",
    ),
    "taxa_classification_mmseqs_taxonomy_votemode": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Specify the weights of the taxonomic assignment.",
        display_name="Taxa Classification MMseqs Taxonomy Vote Mode",
    ),
    "annotation_tool": NextflowParameter(
        type=annotation_database,
        default=annotation_database.pyrodigal,
        section_title=None,
        description="Specify which annotation tool to use for some downstream tools.",
        display_name="Annotation Tool",
    ),
    "save_annotations": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether to save gene annotations in the results directory.",
        display_name="Save Annotations",
    ),
    "annotation_bakta_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Specify a path to a local copy of a BAKTA database.",
        display_name="Annotation Bakta DB",
    ),
    "annotation_bakta_db_downloadtype": NextflowParameter(
        type=typing.Optional[str],
        default="full",
        section_title=None,
        description="Download full or light version of the Bakta database if not supplying own database.",
        display_name="Annotation Bakta DB Download Type",
    ),
    "annotation_bakta_singlemode": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Use the default genome-length optimised mode (rather than the metagenome mode).",
        display_name="Annotation Bakta Single Mode",
    ),
    "annotation_bakta_mincontiglen": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Specify the minimum contig size.",
        display_name="Annotation Bakta Min Contig Length",
    ),
    "annotation_bakta_translationtable": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Specify the genetic code translation table.",
        display_name="Annotation Bakta Translation Table",
    ),
    "annotation_bakta_gram": NextflowParameter(
        type=typing.Optional[str],
        default="?",
        section_title=None,
        description="Specify the type of bacteria to be annotated to detect signaling peptides.",
        display_name="Annotation Bakta Gram",
    ),
    "annotation_bakta_complete": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify that all contigs are complete replicons.",
        display_name="Annotation Bakta Complete",
    ),
    "annotation_bakta_renamecontigheaders": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Changes the original contig headers.",
        display_name="Annotation Bakta Rename Contig Headers",
    ),
    "annotation_bakta_compliant": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Clean the result annotations to standardise them to Genbank/ENA conventions.",
        display_name="Annotation Bakta Compliant",
    ),
    "annotation_bakta_trna": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate tRNA detection & annotation.",
        display_name="Annotation Bakta tRNA",
    ),
    "annotation_bakta_tmrna": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate tmRNA detection & annotation.",
        display_name="Annotation Bakta tmRNA",
    ),
    "annotation_bakta_rrna": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate rRNA detection & annotation.",
        display_name="Annotation Bakta rRNA",
    ),
    "annotation_bakta_ncrna": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate ncRNA detection & annotation.",
        display_name="Annotation Bakta ncRNA",
    ),
    "annotation_bakta_ncrnaregion": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate ncRNA region detection & annotation.",
        display_name="Annotation Bakta ncRNA Region",
    ),
    "annotation_bakta_crispr": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate CRISPR array detection & annotation.",
        display_name="Annotation Bakta CRISPR",
    ),
    "annotation_bakta_skipcds": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip CDS detection & annotation.",
        display_name="Annotation Bakta Skip CDS",
    ),
    "annotation_bakta_pseudo": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate pseudogene detection & annotation.",
        display_name="Annotation Bakta Pseudo",
    ),
    "annotation_bakta_skipsorf": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip sORF detection & annotation.",
        display_name="Annotation Bakta Skip sORF",
    ),
    "annotation_bakta_gap": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate gap detection & annotation.",
        display_name="Annotation Bakta Gap",
    ),
    "annotation_bakta_ori": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate oriC/oriT detection & annotation.",
        display_name="Annotation Bakta Ori",
    ),
    "annotation_bakta_activate_plot": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Activate generation of circular genome plots.",
        display_name="Annotation Bakta Activate Plot",
    ),
    "annotation_prokka_singlemode": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Use the default genome-length optimised mode (rather than the metagenome mode).",
        display_name="Annotation Prokka Single Mode",
    ),
    "annotation_prokka_rawproduct": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Suppress the default clean-up of the gene annotations.",
        display_name="Annotation Prokka Raw Product",
    ),
    "annotation_prokka_kingdom": NextflowParameter(
        type=typing.Optional[str],
        default="Bacteria",
        section_title=None,
        description="Specify the kingdom that the input represents.",
        display_name="Annotation Prokka Kingdom",
    ),
    "annotation_prokka_gcode": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Specify the translation table used to annotate the sequences.",
        display_name="Annotation Prokka GCode",
    ),
    "annotation_prokka_mincontiglen": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Minimum contig size required for annotation (bp).",
        display_name="Annotation Prokka Min Contig Length",
    ),
    "annotation_prokka_evalue": NextflowParameter(
        type=typing.Optional[float],
        default=1e-06,
        section_title=None,
        description="E-value cut-off.",
        display_name="Annotation Prokka E-Value",
    ),
    "annotation_prokka_coverage": NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description="Set the assigned minimum coverage.",
        display_name="Annotation Prokka Coverage",
    ),
    "annotation_prokka_cdsrnaolap": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Allow transfer RNA (trRNA) to overlap coding sequences (CDS).",
        display_name="Annotation Prokka CDS RNA Overlap",
    ),
    "annotation_prokka_rnammer": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Use RNAmmer for rRNA prediction.",
        display_name="Annotation Prokka RNAmmer",
    ),
    "annotation_prokka_compliant": NextflowParameter(
        type=bool,
        default=True,
        section_title=None,
        description="Force contig name to Genbank/ENA/DDJB naming rules.",
        display_name="Annotation Prokka Compliant",
    ),
    "annotation_prokka_addgenes": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Add the gene features for each CDS hit.",
        display_name="Annotation Prokka Add Genes",
    ),
    "annotation_prokka_retaincontigheaders": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Retains contig names.",
        display_name="Annotation Prokka Retain Contig Headers",
    ),
    "annotation_prodigal_singlemode": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether to use Prodigal's single-genome mode for long sequences.",
        display_name="Annotation Prodigal Single Mode",
    ),
    "annotation_prodigal_closed": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Does not allow partial genes on contig edges.",
        display_name="Annotation Prodigal Closed",
    ),
    "annotation_prodigal_transtable": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Specifies the translation table used for gene annotation.",
        display_name="Annotation Prodigal Translation Table",
    ),
    "annotation_prodigal_forcenonsd": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Forces Prodigal to scan for motifs.",
        display_name="Annotation Prodigal Force NonSD",
    ),
    "annotation_pyrodigal_singlemode": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether to use Pyrodigal's single-genome mode for long sequences.",
        display_name="Annotation Pyrodigal Single Mode",
    ),
    "annotation_pyrodigal_closed": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Does not allow partial genes on contig edges.",
        display_name="Annotation Pyrodigal Closed",
    ),
    "annotation_pyrodigal_transtable": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Specifies the translation table used for gene annotation.",
        display_name="Annotation Pyrodigal Translation Table",
    ),
    "annotation_pyrodigal_forcenonsd": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Forces Pyrodigal to scan for motifs.",
        display_name="Annotation Pyrodigal Force NonSD",
    ),
    "save_db": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify whether to save pipeline-downloaded databases in your results directory.",
        display_name="Save Database",
    ),
    "amp_skip_amplify": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip AMPlify during AMP screening.",
        display_name="AMP Skip AMPlify",
    ),
    "amp_skip_ampir": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip ampir during AMP screening.",
        display_name="AMP Skip ampir",
    ),
    "amp_ampir_model": NextflowParameter(
        type=typing.Optional[
            ampir_model
        ],
        default=ampir_model.precursor,
        section_title=None,
        description="Specify which machine learning classification model to use.",
        display_name="AMP ampir Model",
    ),
    "amp_ampir_minlength": NextflowParameter(
        type=typing.Optional[int],
        default=10,
        section_title=None,
        description="Specify minimum protein length for prediction calculation.",
        display_name="AMP ampir Min Length",
    ),
    "amp_run_hmmsearch": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Run hmmsearch during AMP screening.",
        display_name="AMP Run hmmsearch",
    ),
    "amp_hmmsearch_models": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Specify path to the AMP hmm model file(s) to search against. Must have quotes if wildcard used.",
        display_name="AMP hmmsearch Models",
    ),
    "amp_hmmsearch_savealignments": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Saves a multiple alignment of all significant hits to a file.",
        display_name="AMP hmmsearch Save Alignments",
    ),
    "amp_hmmsearch_savetargets": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Save a simple tabular file summarising the per-target output.",
        display_name="AMP hmmsearch Save Targets",
    ),
    "amp_hmmsearch_savedomains": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Save a simple tabular file summarising the per-domain output.",
        display_name="AMP hmmsearch Save Domains",
    ),
    "amp_skip_macrel": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip Macrel during AMP screening.",
        display_name="AMP Skip Macrel",
    ),
    "amp_ampcombi_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to AMPcombi reference database directory (DRAMP).",
        display_name="AMP AMPcombi Database",
    ),
    "amp_ampcombi_parsetables_cutoff": NextflowParameter(
        type=typing.Optional[float],
        default=0.6,
        section_title=None,
        description="Specifies the prediction tools' cut-offs.",
        display_name="AMP AMPcombi Parsetables Cutoff",
    ),
    "amp_ampcombi_parsetables_aalength": NextflowParameter(
        type=typing.Optional[int],
        default=100,
        section_title=None,
        description="Filter out all amino acid fragments shorter than this number.",
        display_name="AMP AMPcombi Parsetables AA Length",
    ),
    "amp_ampcombi_parsetables_dbevalue": NextflowParameter(
        type=typing.Optional[float],
        default=5.0,
        section_title=None,
        description="Remove all DRAMP annotations that have an e-value greater than this value.",
        display_name="AMP AMPcombi Parsetables DB E-Value",
    ),
    "amp_ampcombi_parsetables_hmmevalue": NextflowParameter(
        type=typing.Optional[float],
        default=0.06,
        section_title=None,
        description="Retain HMM hits that have an e-value lower than this.",
        display_name="AMP AMPcombi Parsetables HMM E-Value",
    ),
    "amp_ampcombi_parsetables_windowstopcodon": NextflowParameter(
        type=typing.Optional[int],
        default=60,
        section_title=None,
        description="Assign the number of codons used to look for stop codons, upstream and downstream of the AMP hit.",
        display_name="AMP AMPcombi Parsetables Window Stop Codon",
    ),
    "amp_ampcombi_parsetables_windowtransport": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Assign the number of CDSs upstream and downstream of the AMP to look for a transport protein.",
        display_name="AMP AMPcombi Parsetables Window Transport",
    ),
    "amp_ampcombi_parsetables_removehitswostopcodons": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Remove hits that have no stop codon upstream and downstream of the AMP.",
        display_name="AMP AMPcombi Parsetables Remove Hits Without Stop Codons",
    ),
    "amp_ampcombi_cluster_covmode": NextflowParameter(
        type=typing.Optional[float],
        default=0.0,
        section_title=None,
        description="MMseqs2 coverage mode.",
        display_name="AMP AMPcombi Cluster Coverage Mode",
    ),
    "amp_ampcombi_cluster_sensitivity": NextflowParameter(
        type=typing.Optional[float],
        default=4.0,
        section_title=None,
        description="Remove hits that have no stop codon upstream and downstream of the AMP.",
        display_name="AMP AMPcombi Cluster Sensitivity",
    ),
    "amp_ampcombi_cluster_minmembers": NextflowParameter(
        type=typing.Optional[int],
        default=0,
        section_title=None,
        description="Remove clusters that don't have more AMP hits than this number.",
        display_name="AMP AMPcombi Cluster Min Members",
    ),
    "amp_ampcombi_cluster_mode": NextflowParameter(
        type=typing.Optional[float],
        default=1.0,
        section_title=None,
        description="MMseqs2 clustering mode.",
        display_name="AMP AMPcombi Cluster Mode",
    ),
    "amp_ampcombi_cluster_coverage": NextflowParameter(
        type=typing.Optional[float],
        default=0.8,
        section_title=None,
        description="MMseqs2 alignment coverage.",
        display_name="AMP AMPcombi Cluster Coverage",
    ),
    "amp_ampcombi_cluster_seqid": NextflowParameter(
        type=typing.Optional[float],
        default=0.4,
        section_title=None,
        description="MMseqs2 sequence identity.",
        display_name="AMP AMPcombi Cluster Sequence Identity",
    ),
    "amp_ampcombi_cluster_removesingletons": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Remove any hits that form a single member cluster.",
        display_name="AMP AMPcombi Cluster Remove Singletons",
    ),
    "arg_skip_amrfinderplus": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip AMRFinderPlus during the ARG screening.",
        display_name="ARG Skip AMRFinderPlus",
    ),
    "arg_amrfinderplus_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Specify the path to a local version of the ARMFinderPlus database.",
        display_name="ARG AMRFinderPlus Database",
    ),
    "arg_amrfinderplus_identmin": NextflowParameter(
        type=typing.Optional[float],
        default=-1.0,
        section_title=None,
        description="Minimum percent identity to reference sequence.",
        display_name="ARG AMRFinderPlus Min Identity",
    ),
    "arg_amrfinderplus_coveragemin": NextflowParameter(
        type=typing.Optional[float],
        default=0.5,
        section_title=None,
        description="Minimum coverage of the reference protein.",
        display_name="ARG AMRFinderPlus Min Coverage",
    ),
    "arg_amrfinderplus_translationtable": NextflowParameter(
        type=typing.Optional[int],
        default=11,
        section_title=None,
        description="Specify which NCBI genetic code to use for translated BLAST.",
        display_name="ARG AMRFinderPlus Translation Table",
    ),
    "arg_amrfinderplus_plus": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Add the plus genes to the report.",
        display_name="ARG AMRFinderPlus Plus Genes",
    ),
    "arg_amrfinderplus_name": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Add identified column to AMRFinderPlus output.",
        display_name="ARG AMRFinderPlus Include Name",
    ),
    "arg_skip_deeparg": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip DeepARG during the ARG screening.",
        display_name="ARG Skip DeepARG",
    ),
    "arg_deeparg_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Specify the path to the DeepARG database.",
        display_name="ARG DeepARG Database",
    ),
    "arg_deeparg_db_version": NextflowParameter(
        type=typing.Optional[int],
        default=2,
        section_title=None,
        description="Specify the numeric version number of a user-supplied DeepARG database.",
        display_name="ARG DeepARG Database Version",
    ),
    "arg_deeparg_model": NextflowParameter(
        type=typing.Optional[str],
        default="LS",
        section_title=None,
        description="Specify which model to use (short or long sequences).",
        display_name="ARG DeepARG Model",
    ),
    "arg_deeparg_minprob": NextflowParameter(
        type=typing.Optional[float],
        default=0.8,
        section_title=None,
        description="Specify minimum probability cutoff under which hits are discarded.",
        display_name="ARG DeepARG Min Probability",
    ),
    "arg_deeparg_alignmentevalue": NextflowParameter(
        type=typing.Optional[float],
        default=1e-10,
        section_title=None,
        description="Specify E-value cutoff under which hits are discarded.",
        display_name="ARG DeepARG Alignment E-Value",
    ),
    "arg_deeparg_alignmentidentity": NextflowParameter(
        type=typing.Optional[int],
        default=50,
        section_title=None,
        description="Specify percent identity cutoff for sequence alignment under which hits are discarded.",
        display_name="ARG DeepARG Alignment Identity",
    ),
    "arg_deeparg_alignmentoverlap": NextflowParameter(
        type=typing.Optional[float],
        default=0.8,
        section_title=None,
        description="Specify alignment read overlap.",
        display_name="ARG DeepARG Alignment Overlap",
    ),
    "arg_deeparg_numalignmentsperentry": NextflowParameter(
        type=typing.Optional[int],
        default=1000,
        section_title=None,
        description="Specify minimum number of alignments per entry for DIAMOND step of DeepARG.",
        display_name="ARG DeepARG Num Alignments per Entry",
    ),
    "arg_skip_fargene": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip fARGene during the ARG screening.",
        display_name="ARG Skip fARGene",
    ),
    "arg_fargene_hmmmodel": NextflowParameter(
        type=typing.Optional[str],
        default="class_a,class_b_1_2,class_b_3,class_c,class_d_1,class_d_2,qnr,tet_efflux,tet_rpg,tet_enzyme",
        section_title=None,
        description="Specify comma-separated list of which pre-defined HMM models to screen against.",
        display_name="ARG fARGene HMM Model",
    ),
    "arg_fargene_savetmpfiles": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify to save intermediate temporary files to results directory.",
        display_name="ARG fARGene Save Temp Files",
    ),
    "arg_fargene_score": NextflowParameter(
        type=typing.Optional[float],
        default=None,
        section_title=None,
        description="The threshold score for a sequence to be classified as an (almost) complete gene.",
        display_name="ARG fARGene Score Threshold",
    ),
    "arg_fargene_minorflength": NextflowParameter(
        type=typing.Optional[int],
        default=90,
        section_title=None,
        description="The minimum length of a predicted ORF retrieved from annotating the nucleotide sequences.",
        display_name="ARG fARGene Min ORF Length",
    ),
    "arg_fargene_orffinder": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Defines which ORF finding algorithm to use.",
        display_name="ARG fARGene ORF Finder",
    ),
    "arg_fargene_translationformat": NextflowParameter(
        type=typing.Optional[str],
        default="pearson",
        section_title=None,
        description="The translation table/format to use for sequence annotation.",
        display_name="ARG fARGene Translation Format",
    ),
    "arg_skip_rgi": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip RGI during the ARG screening.",
        display_name="ARG Skip RGI",
    ),
    "arg_rgi_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to user-defined local CARD database.",
        display_name="ARG RGI Database",
    ),
    "arg_rgi_savejson": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Save RGI output .json file.",
        display_name="ARG RGI Save JSON",
    ),
    "arg_rgi_savetmpfiles": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify to save intermediate temporary files in the results directory.",
        display_name="ARG RGI Save Temp Files",
    ),
    "arg_rgi_alignmenttool": NextflowParameter(
        type=typing.Optional[str],
        default="BLAST",
        section_title=None,
        description="Specify the alignment tool to be used.",
        display_name="ARG RGI Alignment Tool",
    ),
    "arg_rgi_includeloose": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Include all of loose, strict, and perfect hits (i.e., ≥ 95% identity) found by RGI.",
        display_name="ARG RGI Include Loose",
    ),
    "arg_rgi_includenudge": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Suppresses the default behavior of RGI with `--arg_rgi_includeloose`.",
        display_name="ARG RGI Include Nudge",
    ),
    "arg_rgi_lowquality": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Include screening of low-quality contigs for partial genes.",
        display_name="ARG RGI Low-Quality Screening",
    ),
    "arg_rgi_data": NextflowParameter(
        type=typing.Optional[str],
        default="NA",
        section_title=None,
        description="Specify a more specific data-type of input (e.g., plasmid, chromosome).",
        display_name="ARG RGI Data Type",
    ),
    "arg_rgi_split_prodigal_jobs": NextflowParameter(
        type=bool,
        default=True,
        section_title=None,
        description="Run multiple prodigal jobs simultaneously for contigs in a fasta file.",
        display_name="ARG RGI Split Prodigal Jobs",
    ),
    "arg_skip_abricate": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip ABRicate during the ARG screening.",
        display_name="ARG Skip ABRicate",
    ),
    "arg_abricate_db_id": NextflowParameter(
        type=typing.Optional[str],
        default="ncbi",
        section_title=None,
        description="Specify the name of the ABRicate database to use.",
        display_name="ARG ABRicate Database ID",
    ),
    "arg_abricate_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to user-defined local ABRicate database directory.",
        display_name="ARG ABRicate Database Path",
    ),
    "arg_abricate_minid": NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description="Minimum percent identity of alignment required for a hit to be considered.",
        display_name="ARG ABRicate Minimum Identity",
    ),
    "arg_abricate_mincov": NextflowParameter(
        type=typing.Optional[int],
        default=80,
        section_title=None,
        description="Minimum percent coverage of alignment required for a hit to be considered.",
        display_name="ARG ABRicate Minimum Coverage",
    ),
    "arg_hamronization_summarizeformat": NextflowParameter(
        type=typing.Optional[str],
        default="tsv",
        section_title=None,
        description="Specifies summary output format.",
        display_name="ARG hAMRonization Summary Format",
    ),
    "arg_skip_argnorm": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip argNorm during ARG screening.",
        display_name="ARG Skip argNorm",
    ),
    "bgc_mincontiglength": NextflowParameter(
        type=typing.Optional[int],
        default=3000,
        section_title=None,
        description="Specify the minimum length of contigs that go into BGC screening.",
        display_name="BGC Minimum Contig Length",
    ),
    "bgc_savefilteredcontigs": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Specify to save the length-filtered (unannotated) FASTAs used for BGC screening.",
        display_name="BGC Save Filtered Contigs",
    ),
    "bgc_skip_antismash": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip antiSMASH during the BGC screening.",
        display_name="BGC Skip antiSMASH",
    ),
    "bgc_antismash_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to user-defined local antiSMASH database.",
        display_name="BGC antiSMASH Database",
    ),
    "bgc_antismash_installdir": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to user-defined local antiSMASH directory.",
        display_name="BGC antiSMASH Install Directory",
    ),
    "bgc_antismash_contigminlength": NextflowParameter(
        type=typing.Optional[int],
        default=3000,
        section_title=None,
        description="Minimum length a contig must have to be screened with antiSMASH.",
        display_name="BGC antiSMASH Minimum Contig Length",
    ),
    "bgc_antismash_cbgeneral": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Turn on clusterblast comparison against database of antiSMASH-predicted clusters.",
        display_name="BGC antiSMASH ClusterBlast General",
    ),
    "bgc_antismash_cbknownclusters": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Turn on clusterblast comparison against known gene clusters from the MIBiG database.",
        display_name="BGC antiSMASH ClusterBlast Known Clusters",
    ),
    "bgc_antismash_cbsubclusters": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Turn on clusterblast comparison against known subclusters responsible for synthesizing precursors.",
        display_name="BGC antiSMASH ClusterBlast Subclusters",
    ),
    "bgc_antismash_ccmibig": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Turn on ClusterCompare comparison against known gene clusters from the MIBiG database.",
        display_name="BGC antiSMASH ClusterCompare MIBiG",
    ),
    "bgc_antismash_smcogtrees": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Generate phylogenetic trees of secondary metabolite group orthologs.",
        display_name="BGC antiSMASH SMCOG Trees",
    ),
    "bgc_antismash_hmmdetectionstrictness": NextflowParameter(
        type=typing.Optional[str],
        default="relaxed",
        section_title=None,
        description="Defines which level of strictness to use for HMM-based cluster detection.",
        display_name="BGC antiSMASH HMM Detection Strictness",
    ),
    "bgc_antismash_pfam2go": NextflowParameter(
        type=bool,
        default=False,
        section_title=None,
        description="Run Pfam to Gene Ontology mapping module.",
        display_name="BGC antiSMASH Pfam2GO",
    ),
    "bgc_antismash_rre": NextflowParameter(
        type=bool,
        default=False,
        section_title=None,
        description="Run RREFinder precision mode on all RiPP gene clusters.",
        display_name="BGC antiSMASH RRE Finder",
    ),
    "bgc_antismash_taxon": NextflowParameter(
        type=typing.Optional[str],
        default="bacteria",
        section_title=None,
        description="Specify which taxonomic classification of input sequence to use.",
        display_name="BGC antiSMASH Taxonomic Classification",
    ),
    "bgc_antismash_tfbs": NextflowParameter(
        type=bool,
        default=False,
        section_title=None,
        description="Run TFBS finder on all gene clusters.",
        display_name="BGC antiSMASH TFBS Finder",
    ),
    "bgc_skip_deepbgc": NextflowParameter(
        type=bool,
        default=None,
        section_title=None,
        description="Skip DeepBGC during the BGC screening.",
        display_name="BGC Skip DeepBGC",
    ),
    "bgc_deepbgc_db": NextflowParameter(
        type=typing.Optional[LatchDir],
        default=None,
        section_title=None,
        description="Path to local DeepBGC database folder.",
        display_name="BGC DeepBGC Database",
    ),
    "bgc_deepbgc_score": NextflowParameter(
        type=typing.Optional[float],
        default=0.5,
        section_title=None,
        description="Average protein-wise DeepBGC score threshold for extracting BGC regions from Pfam sequences.",
        display_name="BGC DeepBGC Score Threshold",
    ),
    "bgc_deepbgc_minnucl": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Minimum BGC nucleotide length.",
        display_name="BGC DeepBGC Minimum Nucleotide Length",
    ),
    "bgc_deepbgc_minproteins": NextflowParameter(
        type=typing.Optional[int],
        default=1,
        section_title=None,
        description="Minimum number of proteins in a BGC.",
        display_name="BGC DeepBGC Minimum Proteins",
    ),
    "multiqc_methods_description": NextflowParameter(
        type=typing.Optional[str],
        default=None,
        section_title=None,
        description="Custom MultiQC yaml file containing HTML including a methods description.",
        display_name="MultiQC Methods Description",
    ),
}
