name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
  pull_request:
  release:
    types: [published]

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data (AMP/ARG)
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/funcscan') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        parameters:
          - "-profile docker,test_preannotated --annotation_tool prodigal"
          - "-profile docker,test --annotation_tool prokka"
          - "-profile docker,test --annotation_tool bakta --annotation_bakta_db_downloadtype light --arg_skip_deeparg --arg_skip_amrfinderplus" # Skip deeparg and amrfinderplus due to otherwise running out of space on GitHub Actions

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data (AMP and ARG workflows)
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{ matrix.parameters }} --outdir ./results

  test_bgc:
    name: Run pipeline with test data (BGC)
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/funcscan') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        parameters:
          - "-profile docker,test_preannotated_bgc --annotation_tool prodigal"
          - "-profile docker,test_bgc --annotation_tool prokka"
          - "-profile docker,test_bgc --annotation_tool bakta --annotation_bakta_db_downloadtype light"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data (BGC workflow)
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{ matrix.parameters }} --outdir ./results --bgc_skip_deepbgc

  test_taxonomy:
    name: Run pipeline with test data (AMP, ARG and BGC taxonomy)
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/funcscan') }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
          - "latest-everything"
        parameters:
          - "-profile docker,test_taxonomy --annotation_tool prodigal" # TODO: Add test_taxonomy_preannotated.config
          - "-profile docker,test_taxonomy --annotation_tool prokka"
          - "-profile docker,test_taxonomy --annotation_tool bakta --annotation_bakta_db_downloadtype light"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Disk space cleanup
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Run pipeline with test data (AMP, ARG and BGC taxonomy workflows)
        run: |
          nextflow run ${GITHUB_WORKSPACE} ${{ matrix.parameters }} --outdir ./results
